import { injectable, inject } from 'tsyringe';
import { IProjectRepository } from '../../../domain/repositories/IProjectRepository';
import { Project } from '../../../domain/entities/Project';

interface CreateProjectInput {
  userId: string;
  name: string;
  description?: string;
}

interface CreateProjectOutput {
  success: boolean;
  data?: {
    project: Project;
  };
  error?: Error;
}

@injectable()
export class CreateProjectUseCase {
  constructor(
    @inject('IProjectRepository') private projectRepository: IProjectRepository
  ) {}

  async execute(input: CreateProjectInput): Promise<CreateProjectOutput> {
    try {
      // Validate input
      if (!input.name || !input.userId) {
        throw new Error('Missing required fields: name and userId are required');
      }

      // Create project domain object
      const project = new Project(
        '', // ID will be generated by repository
        input.userId,
        input.name,
        input.description,
        true, // isActive default
        new Date(),
        new Date()
      );

      // Save to repository
      const savedProject = await this.projectRepository.create(project);

      return {
        success: true,
        data: {
          project: savedProject
        }
      };
    } catch (error) {
      console.error('[CreateProjectUseCase] Error creating project:', error);
      return {
        success: false,
        error: error as Error
      };
    }
  }
}