server:
  port: 3101
  host: 0.0.0.0

database:
  url: file:/data/nano-grazynka.db

transcription:
  provider: openai  # Using OpenAI for gpt-4o-transcribe model
  model: gpt-4o-audio-preview  # GPT-4o-Transcribe: 30% better accuracy than whisper-1 at same cost
  maxFileSizeMB: 25
  supportedFormats:
    - mp3
    - mp4
    - mpeg
    - mpga
    - m4a
    - wav
    - webm

summarization:
  provider: openrouter  # Primary provider (fallback to openai)
  model: google/gemini-2.5-flash  # Latest Gemini Flash model via OpenRouter
  # Alternative models:
  # - google/gemini-2.0-flash-001 (previous version)
  # - google/gemini-2.5-pro-exp-03-25 (higher reasoning)
  # - gpt-4o-mini (OpenAI fallback)
  maxTokens: 2000
  temperature: 0.7
  prompts:
    summary: |
      Summarize the following transcript concisely, capturing key points and main ideas.
      Maintain the original language of the transcript.
    actionPoints: |
      Extract actionable items from the following transcript as a bullet list.
      Present them in the same language as the transcript.

storage:
  uploadDir: /data/uploads
  maxFileAgeDays: 30

processing:
  maxConcurrentJobs: 3
  jobTimeoutMinutes: 30
  retryAttempts: 3