server:
  port: 3101
  host: 0.0.0.0

database:
  url: file:./database.db

transcription:
  provider: openrouter  # Can be 'openai' or 'openrouter'
  apiKey: ""  # Uses OPENAI_API_KEY or OPENROUTER_API_KEY from env
  model: whisper-1  # For OpenAI: 'whisper-1', for OpenRouter: 'openai/whisper-1'
  maxFileSizeMB: 25
  supportedFormats:
    - mp3
    - mp4
    - mpeg
    - mpga
    - m4a
    - wav
    - webm

summarization:
  provider: openrouter  # Primary provider (fallback to openai)
  apiKey: ""  # Uses OPENROUTER_API_KEY or OPENAI_API_KEY from env
  model: google/gemini-2.0-flash-001  # Cost-effective model via OpenRouter
  # Alternative models:
  # - google/gemini-2.5-pro-exp-03-25 (higher reasoning)
  # - gpt-4o-mini (OpenAI fallback)
  maxTokens: 2000  # Increased from 150 for better summaries
  temperature: 0.7

storage:
  type: local
  localPath: ./uploads
  
security:
  jwtSecret: ""
  jwtExpiresIn: "7d"
  rateLimitWindow: 60000
  rateLimitMax: 100

system:
  maxCreditsPerMonth: 60
  resetDay: 1
  
features:
  enableTranscription: true
  enableSummarization: true
  enableExport: true