FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
COPY prisma ./prisma/
RUN npm ci --legacy-peer-deps
RUN npx prisma generate

EXPOSE 3101

CMD ["sh", "-c", "npx prisma generate && npm run dev"]